# playbooks/roles/phpmyadmin/tasks/main.yml
---
- name: Download phpMyAdmin
  get_url:
    url: "{{ phpmyadmin_download_url }}"
    dest: "/tmp/phpmyadmin.tar.gz"
    mode: '0644'

- name: Create installation directory
  file:
    path: "{{ phpmyadmin_install_dir }}"
    state: directory
    mode: '0755'

- name: Extract phpMyAdmin
  unarchive:
    src: "/tmp/phpmyadmin.tar.gz"
    dest: "{{ phpmyadmin_install_dir }}"
    extra_opts: ["--strip-components=1"]
    remote_src: yes

# - name: Create config directory
#   file:
#     path: "{{ phpmyadmin_config_dir }}"
#     state: directory
#     mode: '0755'

- name: check services
  service_facts:

- name: print
  debug:
    msg: "apache2 is {{ ansible_facts.services['apache2.service']['status'] }}"
  when: "'apache2.service' in ansible_facts.services"

- name: print
  debug:
    msg: "nginx is {{ ansible_facts.services['nginx.service']['status'] }}"
  when: "'nginx.service' in ansible_facts.services"

- name: Check Apache service
  ansible.builtin.service:
    name: apache2
    state: started
  register: apache_status
  ignore_errors: yes
  check_mode: true

- name: Check Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
  register: nginx_status
  ignore_errors: yes
  check_mode: true

- name: Set server_type
  set_fact:
    server_type: >-
      {% if apache_status is not failed %}
      apache
      {% elif nginx_status is not failed %}
      nginx
      {% else %}
      unknown
      {% endif %}

- name: debug
  ansible.builtin.debug:
    msg: "service is {{ server_type }}"

- name: Template config file
  template:
    src: config.inc.php.j2
    dest: "{{ phpmyadmin_config_dir }}/config.inc.php"
    mode: '0644'

- name: Creating a virtual host
  template:
    src: apache-phpmyadmin.conf.j2
    dest: /etc/apache2/sites-available/phpmyadmin.conf
    mode: 0644
  notify: Reload Apache
  when:
    - ansible_facts.services['apache2.service'].status == 'enabled'

- name: Enable phpMyAdmin site (Apache)
  file:
    src: /etc/apache2/sites-available/phpmyadmin.conf
    dest: /etc/apache2/sites-enabled/phpmyadmin.conf
    state: link
  when:
    - ansible_facts.services['apache2.service'].status == 'enabled'

- name: Copy Nginx configuration for phpMyAdmin
  template:
    src: phpmyadmin.conf.j2
    dest: /etc/nginx/sites-available/phpmyadmin.conf
  notify: Reload Nginx
  when: server_type == 'nginx'

- name: Enable phpMyAdmin site (Nginx)
  file:
    src: /etc/nginx/sites-available/phpmyadmin.conf
    dest: /etc/nginx/sites-enabled/phpmyadmin.conf
    state: link
  when: server_type == 'nginx'

# - name: Template config file
#   template:
#     src: config.inc.php.j2
#     dest: "{{ phpmyadmin_config_dir }}/config.inc.php"
#     mode: '0644'

# - name: Copy Nginx configuration for phpMyAdmin
#   template:
#     src: phpmyadmin.conf.j2
#     dest: /etc/nginx/sites-available/phpmyadmin.conf
#   notify: Reload Nginx

# - name: Enable phpMyAdmin site
#   file:
#     src: /etc/nginx/sites-available/phpmyadmin.conf
#     dest: /etc/nginx/sites-enabled/phpmyadmin.conf
#     state: link
#   notify: Reload Nginx